name: release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Random Number
        id: randomnumber
        run: echo "::set-output name=randomnumber::$(head -200 /dev/urandom |cksum |cut -f1 -d' ')"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: ${{ steps.randomnumber.outputs.randomnumber }}
