name: release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Random Number
        run: echo "::set-env name=RANDOM_NUMBER::$(head -200 /dev/urandom |cksum |cut -f1 -d' ')"
        env: 
          RANDOM_NUMBER:  1

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "${RANDOM_NUMBER}"
